#!/usr/bin/env bash

function uhm() {
    read -p "Describe what you want to do: " question
    echo "uhm //// $question" | ~/.local/lib/stutterAI/stutterAI.py > ai_command.txt
    status=$?
    cmd=$(echo "$(tail -n 1 ai_command.txt)")
    rm ai_command.txt
    reloadHISTORY="history -w; history -c; history -r"
    case $status in
        1)
            echo "uhm: $cmd"
            ;;
        0)
            read -n1 -r -s -p "(ENTER/ESC) Want to try this command?: $cmd"
            if [[ $REPLY == $'' ]]; then
                history -d $( history | awk 'END{print $1-1}' )
                history -sp $cmd
                eval $reloadHISTORY
                echo -e $'\nPress UP \u2191'
            elif [[ $REPLY == $'\e' ]]; then
                history -d $( history | awk 'END{print $1-1}' )
                eval $reloadHISTORY
                echo -e $'\nI am still learning and may come up with a correct command next time.'
            else
                history -d $( history | awk 'END{print $1-1}' )
                eval $reloadHISTORY
                echo -e $'\nBye!'
            fi
            ;;
        200)
            history -d $( history | awk 'END{print $1-1}' )
            eval $reloadHISTORY
            echo -e $'\nBye!'
            ;;
        210)
            history -d $( history | awk 'END{print $1-1}' )
            eval $reloadHISTORY
            echo -e $'\nYou have hit your openAI rate limit. Try again in 1 minute.'
            ;;
        215)
            history -d $( history | awk 'END{print $1-1}' )
            eval $reloadHISTORY
            echo -e $'\nThe secrets file is missing at location: ~/.stutterAI_secret.json'
            echo -e $'\nThe file should have your API Key with the format:\n{\n    "API_KEY": "YOUR_API_KEY_HERE"\n}'
            ;;
        220)
            history -d $( history | awk 'END{print $1-1}' )
            eval $reloadHISTORY
            echo -e $'\nYour API Key in the secrets file is incorrect: ~/.stutterAI_secret.json'
            ;;
        *)
            history -d $( history | awk 'END{print $1-1}' )
            eval $reloadHISTORY
            echo "Something wonky happened: $cmd"
            ;;
    esac
}